module top(a0_level, a1_level, a2_level, a3_level, b0_level, b1_level, b2_level, b3_level, cin_level, s0, s1, s2, s3, cout);
  input wire [3:0] a0_level;
  input wire [3:0] a1_level;
  input wire [3:0] a2_level;
  input wire [3:0] a3_level;
  input wire [3:0] b0_level;
  input wire [3:0] b1_level;
  input wire [3:0] b2_level;
  input wire [3:0] b3_level;
  input wire [3:0] cin_level;
  output wire s0;
  output wire s1;
  output wire s2;
  output wire s3;
  output wire cout;
  wire __act_0;
  wire __act_1;
  wire __act_2;
  wire __act_3;
  wire __act_4;
  assign __act_0 = (((a0_level > 0) ^ (b0_level > 0)) ^ (cin_level > 0));
  assign __act_1 = (((a1_level > 0) ^ (b1_level > 0)) ^ (((a0_level > 0) & (b0_level > 0)) | ((cin_level > 0) & ((a0_level > 0) ^ (b0_level > 0)))));
  assign __act_2 = (((a2_level > 0) ^ (b2_level > 0)) ^ (((a1_level > 0) & (b1_level > 0)) | ((((a0_level > 0) & (b0_level > 0)) | ((cin_level > 0) & ((a0_level > 0) ^ (b0_level > 0)))) & ((a1_level > 0) ^ (b1_level > 0)))));
  assign __act_3 = (((a3_level > 0) ^ (b3_level > 0)) ^ (((a2_level > 0) & (b2_level > 0)) | ((((a1_level > 0) & (b1_level > 0)) | ((((a0_level > 0) & (b0_level > 0)) | ((cin_level > 0) & ((a0_level > 0) ^ (b0_level > 0)))) & ((a1_level > 0) ^ (b1_level > 0)))) & ((a2_level > 0) ^ (b2_level > 0)))));
  assign __act_4 = (((a3_level > 0) & (b3_level > 0)) | ((((a2_level > 0) & (b2_level > 0)) | ((((a1_level > 0) & (b1_level > 0)) | ((((a0_level > 0) & (b0_level > 0)) | ((cin_level > 0) & ((a0_level > 0) ^ (b0_level > 0)))) & ((a1_level > 0) ^ (b1_level > 0)))) & ((a2_level > 0) ^ (b2_level > 0)))) & ((a3_level > 0) ^ (b3_level > 0))));
  assign s0 = (__act_0) & ~(1'b0);
  assign s1 = (__act_1) & ~(1'b0);
  assign s2 = (__act_2) & ~(1'b0);
  assign s3 = (__act_3) & ~(1'b0);
  assign cout = (__act_4) & ~(1'b0);
endmodule
